using System.Collections.Generic;
using System.Text;
using Verse;

namespace CentralizedClimateControl
{
    public class AirFlowNet
    {
        public float AverageConvertedTemperature;

        public float AverageIntakeTemperature;

        public List<CompAirFlow> Connectors = new List<CompAirFlow>();
        public List<CompAirFlowConsumer> Consumers = new List<CompAirFlowConsumer>();
        public float FlowEfficiency = 1.0f;

        public AirFlowType FlowType;
        public List<CompAirFlowProducer> Producers = new List<CompAirFlowProducer>();
        public List<CompAirFlowTempControl> TempControls = new List<CompAirFlowTempControl>();

        public float ThermalCapacity;
        public float ThermalEfficiency = 1.0f;

        public int GridID { get; set; } = -2;

        public float CurrentIntakeAir { get; private set; }

        public float CurrentExhaustAir { get; private set; }

        /// <summary>
        ///     Tick the Producers of Air Flow.
        ///     We calculate the Intake Temperature here and the Total Air generated by the network.
        /// </summary>
        private void TickProducers()
        {
            var airFlow = 0.0f;
            var tempSum = 0.0f;
            var activeCount = 0;

            foreach (var producer in Producers)
            {
                if (!producer.IsOperating() || !producer.IsActive())
                {
                    continue;
                }

                airFlow += producer.CurrentAirFlow;
                tempSum += producer.IntakeTemperature;
                activeCount++;
            }

            if (activeCount > 0)
            {
                AverageIntakeTemperature = tempSum / (float)activeCount;
                CurrentIntakeAir = airFlow;
            } 
            else 
            {
                AverageIntakeTemperature = 0.0f;
            }
            CurrentIntakeAir = airFlow;
        }

        /// <summary>
        ///     Process the Consumers for a Tick. Consumers are the ones who consume Air Flow. They can be Vents (for now).
        ///     We calculate the total Exhaust capacity of the Network. This Exhaust Capacity is used by the Flow Efficiency
        ///     Attribute.
        /// </summary>
        private void TickConsumers()
        {
            var airFlow = 0.0f;

            foreach (var consumer in Consumers)
            {
                if (!consumer.IsOperating())
                {
                    continue;
                }

                airFlow += consumer.ExhaustAirFlow;
            }

            CurrentExhaustAir = airFlow;
        }

        /// <summary>
        ///     Process the Buildings that Control Climate. Generally, the Climate Control Units.
        ///     Here, we process variables to be used to Thermal Efficiency.
        /// </summary>
        private void TickTempControllers()
        {
            var tempSum = 0.0f;
            var thermalCapacity = 0.0f;
            var activeCount = 0;

            foreach (var compAirFlowTempControl in TempControls)
            {
                if (!compAirFlowTempControl.IsOperating() || !compAirFlowTempControl.IsActive())
                {
                    continue;
                }

                tempSum += compAirFlowTempControl.ConvertedTemperature;
                thermalCapacity += compAirFlowTempControl.ThermalCapacity;
                activeCount++;
            }

            // No Temperature Controllers -> Then Use the Intake Temperature directly.
            if (activeCount > 0)
            {
                ThermalCapacity = thermalCapacity;
                AverageConvertedTemperature = tempSum / (float)activeCount;
            }
            else
            {
                ThermalCapacity = CurrentIntakeAir;
                AverageConvertedTemperature = AverageIntakeTemperature;
            }
        }

        /// <summary>
        ///     Register a Producer of Air Flow in the Network.
        /// </summary>
        /// <param name="producer">The Producer's Component</param>
        public void RegisterProducer(CompAirFlowProducer producer)
        {
            if (Producers.Contains(producer))
            {
                Log.Error("AirFlowNet registered producer it already had: " + producer);
                return;
            }

            Producers.Add(producer);
        }

        /// <summary>
        ///     De-register a Producer in the Network.
        /// </summary>
        /// <param name="producer">The Producer's Component</param>
        public void DeregisterProducer(CompAirFlowProducer producer)
        {
            if (!Producers.Contains(producer))
            {
                Log.Error("AirFlowNet de-registered producer it already removed: " + producer);
                return;
            }

            Producers.Remove(producer);
        }

        /// <summary>
        ///     Process one Tick of the Air Flow Network. Here we process the Producers, Consumers and Climate Controllers.
        ///     We Calculate the Flow Efficiency (FE) and Thermal Efficiency (TE).
        ///     FE & TEs are recorded for each individual network.
        /// </summary>
        public void AirFlowNetTick()
        {
            TickProducers();
            TickTempControllers();
            TickConsumers();

            if (CurrentIntakeAir > 0)
            {
                ThermalEfficiency = ThermalCapacity / CurrentIntakeAir;
            }
            else
            {
                ThermalEfficiency = 0.0f;
            }

            if (CurrentExhaustAir > 0)
            {
                FlowEfficiency = CurrentIntakeAir / CurrentExhaustAir;

                if (FlowEfficiency > 1.0f)
                {
                    FlowEfficiency = 1.0f;
                }
            }
            else
            {
                FlowEfficiency = 0.0f;
            }
        }

        /// <summary>
        ///     Print the Debug String for this Network
        /// </summary>
        /// <returns>Multi-line String containing Output</returns>
        public string DebugString()
        {
            var stringBuilder = new StringBuilder();
            stringBuilder.AppendLine("------------");
            stringBuilder.AppendLine("AIRFLOW NET:");
            stringBuilder.AppendLine("  Prodcued AirFlow: " + CurrentIntakeAir);
            stringBuilder.AppendLine("  AverageIntakeTemperature: " + AverageIntakeTemperature);
            stringBuilder.AppendLine("  AverageConvertedTemperature: " + AverageConvertedTemperature);

            stringBuilder.AppendLine("  Producers: ");
            foreach (var current in Producers)
            {
                stringBuilder.AppendLine("      " + current.parent);
            }

            stringBuilder.AppendLine("  TempControls: ");
            foreach (var current in TempControls)
            {
                stringBuilder.AppendLine("      " + current.parent);
            }

            stringBuilder.AppendLine("  Consumers: ");
            foreach (var current in Consumers)
            {
                stringBuilder.AppendLine("      " + current.parent);
            }

            stringBuilder.AppendLine("------------");
            return stringBuilder.ToString();
        }
    }
}